"""Aggregate every results/<model>/results.json into one combined leaderboard.

Per-model reports answer "how fast is THIS model on Arm?"; the leaderboard
answers "which model should I deploy on my Arm box?". For each model we pick
its best configuration (highest decode tok/s, preferring KleidiAI-on) and rank.

Cost: tokens/sec converts directly to $/million-tokens for a given instance
price: $/Mtok = price_per_hour / (tok/s * 3600 / 1e6). On GitHub Actions
runners (or Oracle free tier) the price is $0.00 — which IS the headline — but
pass --price-per-hour to model a paid Arm instance instead.
"""
from __future__ import annotations

from pathlib import Path
from typing import List, Optional

from . import util
from .report import kleidiai_speedup, _svg_bars


def collect(results_dir: Optional[Path] = None) -> List[dict]:
    """Load every results/<model>/results.json into a list of run dicts."""
    root = results_dir or util.RESULTS
    runs = []
    for f in sorted(root.glob("*/results.json")):
        try:
            runs.append(util.load_json(f))
        except Exception as e:
            util.log(f"skipping unreadable {f}: {e}")
    return runs


def best_row(results: List[dict]) -> Optional[dict]:
    """Best decode config for a model: prefer KleidiAI-on rows, then max tok/s."""
    on = [r for r in results if r["build"] == "kleidiai-on"]
    pool = on or results
    return max(pool, key=lambda r: r["decode_tps"], default=None)


def cost_per_mtok(decode_tps: float, price_per_hour: float) -> float:
    if decode_tps <= 0:
        return 0.0
    return round(price_per_hour / (decode_tps * 3600 / 1e6), 4)


def build_leaderboard(price_per_hour: float = 0.0,
                      results_dir: Optional[Path] = None) -> Optional[Path]:
    runs = collect(results_dir)
    if not runs:
        util.log("no results/<model>/results.json files found — run a sweep first")
        return None

    rows = []
    for run in runs:
        best = best_row(run["results"])
        if not best:
            continue
        # Gain at the best row's own quant — e.g. when Q8_0+KleidiAI wins the
        # ranking, show the Q8_0 gain (the real i8mm win), not Q4_0's ~1.0x.
        speed = kleidiai_speedup(run["results"], best["quant"])
        rows.append({
            "model": run["model"],
            "quant": best["quant"],
            "build": best["build"],
            "threads": best["threads"],
            "size_gb": best["size_gb"],
            "prefill_tps": best["prefill_tps"],
            "decode_tps": best["decode_tps"],
            "ttft_ms": best["ttft_ms"],
            "kleidiai_decode_speedup": speed.get("decode_speedup", "-"),
            "cost_per_mtok": cost_per_mtok(best["decode_tps"], price_per_hour),
            "host": run.get("host", {}).get("cpu_model", "?"),
        })
    rows.sort(key=lambda r: r["decode_tps"], reverse=True)

    out_dir = results_dir or util.RESULTS
    (out_dir / "leaderboard.md").write_text(_markdown(rows, price_per_hour))
    (out_dir / "leaderboard.html").write_text(_html(rows, price_per_hour))
    util.log(f"leaderboard -> {out_dir/'leaderboard.md'} and leaderboard.html")
    return out_dir


def _cost_header(price_per_hour: float) -> str:
    return (f"$/Mtok @ ${price_per_hour}/hr" if price_per_hour > 0
            else "$/Mtok (free host)")


def _markdown(rows: List[dict], price_per_hour: float) -> str:
    lines = [
        "# KleidiBench leaderboard",
        "",
        f"Best configuration per model (highest decode tok/s, KleidiAI-on preferred). "
        f"Host: {rows[0]['host'] if rows else '?'}.",
        "",
        f"| Rank | Model | Best config | Size (GB) | Prefill tok/s | Decode tok/s | "
        f"TTFT (ms) | KleidiAI decode gain | {_cost_header(price_per_hour)} |",
        "|-----:|-------|-------------|----------:|--------------:|-------------:|"
        "----------:|---------------------:|------:|",
    ]
    for i, r in enumerate(rows, 1):
        cost = "0.00 (free)" if price_per_hour == 0 else f"{r['cost_per_mtok']}"
        gain = (f"{r['kleidiai_decode_speedup']}x"
                if r["kleidiai_decode_speedup"] != "-" else "-")
        lines.append(
            f"| {i} | {r['model']} | {r['quant']} / {r['build']} @ {r['threads']}t | "
            f"{r['size_gb']} | {r['prefill_tps']} | {r['decode_tps']} | "
            f"{r['ttft_ms']} | {gain} | {cost} |")
    lines += ["", "_Generated by `kleidibench leaderboard`. Per-model detail in "
                  "`results/<model>/report.md`._", ""]
    return "\n".join(lines)


def _html(rows: List[dict], price_per_hour: float) -> str:
    chart = _svg_bars([(r["model"], r["decode_tps"]) for r in reversed(rows)],
                      title="Decode tok/s by model (best config)")
    trows = "".join(
        f"<tr><td>{i}</td><td>{r['model']}</td>"
        f"<td>{r['quant']} / {r['build']} @ {r['threads']}t</td>"
        f"<td>{r['size_gb']}</td><td>{r['prefill_tps']}</td>"
        f"<td>{r['decode_tps']}</td><td>{r['ttft_ms']}</td>"
        f"<td>{r['kleidiai_decode_speedup']}"
        f"{'x' if r['kleidiai_decode_speedup'] != '-' else ''}</td>"
        f"<td>{'0.00 (free)' if price_per_hour == 0 else r['cost_per_mtok']}</td></tr>"
        for i, r in enumerate(rows, 1))
    host = rows[0]["host"] if rows else "?"
    return f"""<!doctype html><html><head><meta charset="utf-8">
<title>KleidiBench leaderboard</title><style>
body{{font-family:-apple-system,Segoe UI,Roboto,sans-serif;max-width:900px;
margin:2rem auto;padding:0 1rem;color:#12203a}}
table{{border-collapse:collapse;width:100%;margin-top:1rem}}
th,td{{border:1px solid #d7dEEA;padding:.4rem .6rem;text-align:right}}
td:nth-child(2),td:nth-child(3){{text-align:left}}
thead{{background:#0b7285;color:#fff}}
.sub{{color:#5b6b86}} .bar{{fill:#0b7285}} .barlabel{{font-size:12px;fill:#12203a}}
</style></head><body>
<h1>KleidiBench leaderboard</h1>
<p class="sub">Best configuration per model &middot; {host}</p>
{chart}
<table><thead><tr><th>#</th><th>Model</th><th>Best config</th><th>Size GB</th>
<th>Prefill t/s</th><th>Decode t/s</th><th>TTFT ms</th><th>KleidiAI gain</th>
<th>{_cost_header(price_per_hour)}</th></tr></thead><tbody>{trows}</tbody></table>
<p class="sub">Generated by <code>kleidibench leaderboard</code>.</p>
</body></html>"""
